version: '3'
services:
  database:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33060:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=terracost
      - MYSQL_DATABASE=terracost_test
