version: '3'
services:
  terracost:
    image: cycloid/golang:1.15.6
    volumes:
      - .:/go/src/github.com/cycloidio/terracost
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/github.com/cycloidio/terracost
    networks:
      terracost-subnet:
        ipv4_address: 172.44.0.3

  database:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33060:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=terracost
      - MYSQL_DATABASE=terracost_test
    networks:
      terracost-subnet:
        ipv4_address: 172.44.0.2

networks:
  terracost-subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.0.0/16
