// Code generated by "enumer -type=Field -output=field_gen.go -linecomment"; DO NOT EDIT.

package field

import (
	"fmt"
	"strings"
)

const _FieldName = "SKUCapacityStatusGroupInstance TypeLocationOperating SystemPre Installed S/WProduct FamilyserviceCodeTenancyusageTypeVolume API NameVolume TypeCache EngineDatabase EngineDatabase EditionDeployment OptionLicense ModelCurrencyPricePerUnitStartingRangeTermTypeUnit"

var _FieldIndex = [...]uint16{0, 3, 17, 22, 35, 43, 59, 76, 90, 101, 108, 117, 132, 143, 155, 170, 186, 203, 216, 224, 236, 249, 257, 261}

const _FieldLowerName = "skucapacitystatusgroupinstance typelocationoperating systempre installed s/wproduct familyservicecodetenancyusagetypevolume api namevolume typecache enginedatabase enginedatabase editiondeployment optionlicense modelcurrencypriceperunitstartingrangetermtypeunit"

func (i Field) String() string {
	if i >= Field(len(_FieldIndex)-1) {
		return fmt.Sprintf("Field(%d)", i)
	}
	return _FieldName[_FieldIndex[i]:_FieldIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FieldNoOp() {
	var x [1]struct{}
	_ = x[SKU-(0)]
	_ = x[CapacityStatus-(1)]
	_ = x[Group-(2)]
	_ = x[InstanceType-(3)]
	_ = x[Location-(4)]
	_ = x[OperatingSystem-(5)]
	_ = x[PreInstalledSW-(6)]
	_ = x[ProductFamily-(7)]
	_ = x[ServiceCode-(8)]
	_ = x[Tenancy-(9)]
	_ = x[UsageType-(10)]
	_ = x[VolumeAPIName-(11)]
	_ = x[VolumeType-(12)]
	_ = x[CacheEngine-(13)]
	_ = x[DatabaseEngine-(14)]
	_ = x[DatabaseEdition-(15)]
	_ = x[DeploymentOption-(16)]
	_ = x[LicenseModel-(17)]
	_ = x[Currency-(18)]
	_ = x[PricePerUnit-(19)]
	_ = x[StartingRange-(20)]
	_ = x[TermType-(21)]
	_ = x[Unit-(22)]
}

var _FieldValues = []Field{SKU, CapacityStatus, Group, InstanceType, Location, OperatingSystem, PreInstalledSW, ProductFamily, ServiceCode, Tenancy, UsageType, VolumeAPIName, VolumeType, CacheEngine, DatabaseEngine, DatabaseEdition, DeploymentOption, LicenseModel, Currency, PricePerUnit, StartingRange, TermType, Unit}

var _FieldNameToValueMap = map[string]Field{
	_FieldName[0:3]:          SKU,
	_FieldLowerName[0:3]:     SKU,
	_FieldName[3:17]:         CapacityStatus,
	_FieldLowerName[3:17]:    CapacityStatus,
	_FieldName[17:22]:        Group,
	_FieldLowerName[17:22]:   Group,
	_FieldName[22:35]:        InstanceType,
	_FieldLowerName[22:35]:   InstanceType,
	_FieldName[35:43]:        Location,
	_FieldLowerName[35:43]:   Location,
	_FieldName[43:59]:        OperatingSystem,
	_FieldLowerName[43:59]:   OperatingSystem,
	_FieldName[59:76]:        PreInstalledSW,
	_FieldLowerName[59:76]:   PreInstalledSW,
	_FieldName[76:90]:        ProductFamily,
	_FieldLowerName[76:90]:   ProductFamily,
	_FieldName[90:101]:       ServiceCode,
	_FieldLowerName[90:101]:  ServiceCode,
	_FieldName[101:108]:      Tenancy,
	_FieldLowerName[101:108]: Tenancy,
	_FieldName[108:117]:      UsageType,
	_FieldLowerName[108:117]: UsageType,
	_FieldName[117:132]:      VolumeAPIName,
	_FieldLowerName[117:132]: VolumeAPIName,
	_FieldName[132:143]:      VolumeType,
	_FieldLowerName[132:143]: VolumeType,
	_FieldName[143:155]:      CacheEngine,
	_FieldLowerName[143:155]: CacheEngine,
	_FieldName[155:170]:      DatabaseEngine,
	_FieldLowerName[155:170]: DatabaseEngine,
	_FieldName[170:186]:      DatabaseEdition,
	_FieldLowerName[170:186]: DatabaseEdition,
	_FieldName[186:203]:      DeploymentOption,
	_FieldLowerName[186:203]: DeploymentOption,
	_FieldName[203:216]:      LicenseModel,
	_FieldLowerName[203:216]: LicenseModel,
	_FieldName[216:224]:      Currency,
	_FieldLowerName[216:224]: Currency,
	_FieldName[224:236]:      PricePerUnit,
	_FieldLowerName[224:236]: PricePerUnit,
	_FieldName[236:249]:      StartingRange,
	_FieldLowerName[236:249]: StartingRange,
	_FieldName[249:257]:      TermType,
	_FieldLowerName[249:257]: TermType,
	_FieldName[257:261]:      Unit,
	_FieldLowerName[257:261]: Unit,
}

var _FieldNames = []string{
	_FieldName[0:3],
	_FieldName[3:17],
	_FieldName[17:22],
	_FieldName[22:35],
	_FieldName[35:43],
	_FieldName[43:59],
	_FieldName[59:76],
	_FieldName[76:90],
	_FieldName[90:101],
	_FieldName[101:108],
	_FieldName[108:117],
	_FieldName[117:132],
	_FieldName[132:143],
	_FieldName[143:155],
	_FieldName[155:170],
	_FieldName[170:186],
	_FieldName[186:203],
	_FieldName[203:216],
	_FieldName[216:224],
	_FieldName[224:236],
	_FieldName[236:249],
	_FieldName[249:257],
	_FieldName[257:261],
}

// FieldString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FieldString(s string) (Field, error) {
	if val, ok := _FieldNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _FieldNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Field values", s)
}

// FieldValues returns all values of the enum
func FieldValues() []Field {
	return _FieldValues
}

// FieldStrings returns a slice of all String values of the enum
func FieldStrings() []string {
	strs := make([]string, len(_FieldNames))
	copy(strs, _FieldNames)
	return strs
}

// IsAField returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Field) IsAField() bool {
	for _, v := range _FieldValues {
		if i == v {
			return true
		}
	}
	return false
}
