// Code generated by "enumer -type=Service -output=service_string.go -linecomment=true"; DO NOT EDIT.

package google

import (
	"fmt"
	"strings"
)

const _ServiceName = "Compute Engine"

var _ServiceIndex = [...]uint8{0, 14}

const _ServiceLowerName = "compute engine"

func (i Service) String() string {
	if i >= Service(len(_ServiceIndex)-1) {
		return fmt.Sprintf("Service(%d)", i)
	}
	return _ServiceName[_ServiceIndex[i]:_ServiceIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ServiceNoOp() {
	var x [1]struct{}
	_ = x[ComputeEngine-(0)]
}

var _ServiceValues = []Service{ComputeEngine}

var _ServiceNameToValueMap = map[string]Service{
	_ServiceName[0:14]:      ComputeEngine,
	_ServiceLowerName[0:14]: ComputeEngine,
}

var _ServiceNames = []string{
	_ServiceName[0:14],
}

// ServiceString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ServiceString(s string) (Service, error) {
	if val, ok := _ServiceNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _ServiceNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Service values", s)
}

// ServiceValues returns all values of the enum
func ServiceValues() []Service {
	return _ServiceValues
}

// ServiceStrings returns a slice of all String values of the enum
func ServiceStrings() []string {
	strs := make([]string, len(_ServiceNames))
	copy(strs, _ServiceNames)
	return strs
}

// IsAService returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Service) IsAService() bool {
	for _, v := range _ServiceValues {
		if i == v {
			return true
		}
	}
	return false
}
